// MODIFICA ESTA URL POR LA DEL SERVICIO WEB DESPUES DE HABERLO DESPLEGADO
const AS_URL_BASE = "https://script.google.com/macros/s/AKfycbxyBIM7GiD33vT0WSMM2ez-8fH-H3lIUVDkFf2_G6vllqoymZOSRxgZzCtDbP3Givww/exec";
